version: '3.1'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lista-compras-app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
