name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host vps\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/deploy_key\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 700 ~/.ssh

      - name: Upload .env file to VPS
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SYNCHRONIZE: ${{ secrets.DB_SYNCHRONIZE }}
          DB_LOGGING: ${{ secrets.DB_LOGGING }}
        run: |
          ssh vps '
            echo "NODE_ENV=$NODE_ENV\nDB_HOST=$DB_HOST\nDB_PORT=$DB_PORT\nDB_USER=$DB_USER\nDB_PASSWORD=$DB_PASSWORD\nDB_NAME=$DB_NAME\nDB_SYNCHRONIZE=$DB_SYNCHRONIZE\nDB_LOGGING=$DB_LOGGING" > /root/projects/compra-ai-api/.env
          '

      - name: Deploy with Docker Compose
        run: |
          ssh vps '
            cd /root/projects/compra-ai-api &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d --build
          '
