name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host vps\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/id_ed25519\n\tStrictHostKeyChecking no" >> ~/.ssh/config
          chmod 700 ~/.ssh

      - name: Upload .env file to VPS
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SYNCHRONIZE: ${{ secrets.DB_SYNCHRONIZE }}
          DB_LOGGING: ${{ secrets.DB_LOGGING }}
        run: |
          ssh vps '
            echo "NODE_ENV=$NODE_ENV" > /projects/compra-ai-api.env &&
            echo "DB_HOST=$DB_HOST" >> /projects/compra-ai-api.env &&
            echo "DB_PORT=$DB_PORT" >> /projects/compra-ai-api.env &&
            echo "DB_USER=$DB_USER" >> /projects/compra-ai-api.env &&
            echo "DB_PASSWORD=$DB_PASSWORD" >> /projects/compra-ai-api.env &&
            echo "DB_NAME=$DB_NAME" >> /projects/compra-ai-api.env &&
            echo "DB_SYNCHRONIZE=$DB_SYNCHRONIZE" >> /projects/compra-ai-api.env &&
            echo "DB_LOGGING=$DB_LOGGING" >> /projects/compra-ai-api.env
          '

      - name: Deploy with Docker Compose
        run: |
          ssh vps '
            cd /projects/compra-ai-api &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d --build
          '
